### ISSUE TITLE
/music auto plays the music before the match is started.

### ISSUE THREAD

**Issue by zix3r** [yummypasta/MinecraftManhunt#16]
## Describe the bug
Setting the music to auto starts the music even before the game is started with the /start command and and sometimes it's not even the right one, like for example, I set the hunters and speedrunners, set the /music auto, and when I start it, no music 

## Potential Causes
I just did /music auto and it starts playing after a sec.

## Environment Info
**Plugin version:** 1.3

**Bukkit/Spigot server version:** 1.16.4

## Configuration file
Sending us your plugin `config.yml` file may help in diagnosing the issue. Paste the contents of the plugin's config file here: (feel free to omit your Discord token for security reasons)
```yaml
# How long the hunters should get blindness and slowness when the match starts.
headStartDuration: 15
compassEnabledInNether: false
sendUsageData: true
enableDiscord: true
discordToken: xxxxx
ip: verygood.ip
processDiscordCommands: false
discordServerId: 773923702651092992
musicChannelId: 775382857652633600
hunterRoleId: XXXXX
runnerRoleId: XXXXX
spectatorRoleId: XXXXX
uuid: 100c7e93-1313-4290-8941-aca8dea14701
```

## Server Logs
Please check your Server Console for any warnings or errors created by the plugin. If any are any, please copy and paste them here:
```
None.
```

## Anything else?
Nothing else.
