### ISSUE TITLE
When someone dies before the game starts, they get a compass

### ISSUE THREAD

**Issue by zix3r** [yummypasta/MinecraftManhunt#18]
## Describe the bug
When someone dies before the game is started, they get a compass.
## Potential Causes
Killing someone before the game starts.

## Environment Info
**Plugin version:** 1.3.1

**Bukkit/Spigot server version:** 1.16.4

## Configuration file
Sending us your plugin `config.yml` file may help in diagnosing the issue. Paste the contents of the plugin's config file here: (feel free to omit your Discord token for security reasons)
```yaml
# How long the hunters should get blindness and slowness when the match starts.
headStartDuration: 20
compassEnabledInNether: false
sendUsageData: false
enableDiscord: true
discordToken: xxxxx
ip: servas.ggs.gg
processDiscordCommands: false
discordServerId: 773923702651092992
musicChannelId: 773923702651092996
hunterRoleId: XXXXX
runnerRoleId: XXXXX
spectatorRoleId: XXXXX
uuid: 100c7e93-1313-4290-8941-aca8dea14701
```

## Server Logs
Please check your Server Console for any warnings or errors created by the plugin. If any are any, please copy and paste them here:
```
None.
```

## Anything else?
Nope.
