### ISSUE TITLE
/hunter, /speedrunner, /spectator, and /start have internal errors

### ISSUE THREAD

**Issue by icedchai** [yummypasta/MinecraftManhunt#23]
## Describe the bug
Every time I use any of those commands, it says that there's an internal error. The commands that make teams, in the end, are successful, but /start doesn't start the game.

## Environment Info
**Plugin version:** 1.3.2

**Bukkit/Spigot server version:** 1.16.1

## Configuration file
Sending us your plugin `config.yml` file may help in diagnosing the issue. Paste the contents of the plugin's config file here: (feel free to omit your Discord token for security reasons)
```yaml
Paste your config.yml file here

# How long the hunters should get blindness and slowness when the match starts.
headStartDuration: 30
compassEnabledInNether: true
sendUsageData: true
enableDiscord: true
discordToken: xxx
ip: a minecraft server
processDiscordCommands: truetry
discordServerId: xxx
musicChannelId: xxx
hunterRoleId: xxx
runnerRoleId: xxx
spectatorRoleId: xxx
uuid: bebddb51-a11f-4668-89bc-98f7ff6de941


```

## Server Logs
Please check your Server Console for any warnings or errors created by the plugin. If any are any, please copy and paste them here:
```
Paste relevant console warnings/errors here
```

[console log.txt](https://github.com/yummypasta/MinecraftManhunt/files/5541352/console.log.txt)

**Comment by yummypasta** [comment]
Hi @icedchai,
Thanks for using the plugin.

It looks like the Discord bot you created doesn't have the permissions in your Discord server to assign roles.

**To Fix:**
1. Create a role that's only assigned to the Discord bot if you don't have one already.
2. Drag the bot's role above the `hunter`, `runner`, and `spectator` roles you created in Discord.
3. Make sure your bot has administrator permissions, or if you'd rather not give it that, give it the following permissions:
   - Manage roles
   - Send messages
   - Read message history
   - Connect and speak in VC
   - Use voice activity

If this works, feel free to close this issue. Otherwise, send a reply!

**Comment by icedchai** [comment]
so if my bot isnt working, then the game won't start?

**Comment by yummypasta** [comment]
The plugin won't work if the Discord integration has an error. However, if you can't figure out how to configure the bot, you can disable role assignment by changing the Role IDs in your config.yml file to this:
```yml
hunterRoleId: ""
runnerRoleId: ""
spectatorRoleId: ""
```

If you want to disable Discord integration entirely, you can set `enableDiscord` to `false`.
