### ISSUE TITLE
cant hear discord bot

### ISSUE THREAD

**Issue by pokeyjojo** [yummypasta/MinecraftManhunt#33]
## Describe the bug
A clear and concise description of what the bug is. i can't hear the music bot everything seems to be working though

## Potential Causes
If you did anything specific to trigger the bug, write it here.
made the bot
## Environment Info
**Plugin version:** X.X.X
1.3.3.2
**Bukkit/Spigot server version:** X.X.X
1.16.4
## Configuration file
Sending us your plugin `config.yml` file may help in diagnosing the issue. Paste the contents of the plugin's config file here: (feel free to omit your Discord token for security reasons)
```yaml
Paste your config.yml file here
```# How long the hunters should get blindness and slowness when the match starts.
headStartDuration: 30
compassEnabledInNether: true
sendUsageData: true
enableDiscord: true
discordToken: censord(dont want you to see)
ip: a minecraft server
processDiscordCommands: true
discordServerId: 755250620906340493
musicChannelId: 782278143321964554
hunterRoleId: XXXXX
runnerRoleId: XXXXX
spectatorRoleId: XXXXX
uuid: ea862964-1768-48af-9fa6-feaade9a2dd1

## Server Logs
Please check your Server Console for any warnings or errors created by the plugin. If any are any, please copy and paste them here:
```
Paste relevant console warnings/errors here
```
Can't keep up! Is the server overloaded? Running 43271ms or 865 ticks behind

## Anything else?
Add any other context about the problem here.
