### ISSUE TITLE
Manhunt Compass not working for multiple players

### ISSUE THREAD

**Issue by Phoenic1** [yummypasta/MinecraftManhunt#41]
## Describe the bug
Tracking Compass only working for one of three hunters
## Potential Causes
If you did anything specific to trigger the bug, write it here.
It happens every time no matter what, restarting the server did not fix it
## Environment Info
**Plugin version:** 1.3.3.2
**Bukkit/Spigot server version:** Bukkit 1.16.1 
## Configuration file
Sending us your plugin `config.yml` file may help in diagnosing the issue. Paste the contents of the plugin's config file here: (feel free to omit your Discord token for security reasons)
```yaml
Paste your config.yml file here

# How long the hunters should get blindness and slowness when the match starts.
headStartDuration: 25
compassEnabledInNether: true
sendUsageData: true
enableDiscord: false
discordToken: omitted
ip: omitted
processDiscordCommands: true
discordServerId: omitted
musicChannelId: omitted
hunterRoleId: omitted
runnerRoleId: omitted
spectatorRoleId: omitted
uuid: 1764ca68-1049-4943-816b-9a9bb47cbd56
```
## Server Logs

No errors

## Anything else?
I really just don't understand, sometimes it works and others it just doesn't. This is on a private hosted server. Tried with all players opped or not, nothing changed.
