### ISSUE TITLE
Compass is now targeting null

### ISSUE THREAD

**Issue by Futuristically** [yummypasta/MinecraftManhunt#56]
## Describe the bug
The compass couldn't track certain names and calls them null, such as Futuristically or Futurist, but other names like Afkinator and fosterguy, the compass does work

## Potential Causes
If you did anything specific to trigger the bug, write it here.
I did not do anything to trigger the bug, it was there from the beginning

## Environment Info
**Plugin version:** 1.3.3.2 and 1.3.2

**Bukkit/Spigot server version:** Spigot 1.16.3

## Configuration file
Sending us your plugin `config.yml` file may help in diagnosing the issue. Paste the contents of the plugin's config file here: (feel free to omit your Discord token for security reasons)
```yaml
Paste your config.yml file here
```# How long the hunters should get blindness and slowness when the match starts.
headStartDuration: 30
compassEnabledInNether: true
sendUsageData: true
enableDiscord: false
discordToken: XXXXX
ip: a minecraft server
processDiscordCommands: true
discordServerId: XXXXX
musicChannelId: XXXXX
hunterRoleId: XXXXX
runnerRoleId: XXXXX
spectatorRoleId: XXXXX
uuid: 0d3a5dce-9fa8-4263-8a9b-1a94ab4b6846

## Server Logs
Please check your Server Console for any warnings or errors created by the plugin. If any are any, please copy and paste them here:
```

[11:20:20] [Server thread/WARN]: [MinecraftManhunt] Task #6 for MinecraftManhunt v1.3.3.2 generated an exception
--
634 | java.lang.IllegalArgumentException: Name cannot be null
635 | at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
636 | at org.bukkit.craftbukkit.v1_16_R2.CraftServer.getPlayer(CraftServer.java:523) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
637 | at org.bukkit.Bukkit.getPlayer(Bukkit.java:432) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
638 | at com.yoonicode.minecraftmanhunt.PluginCommands.UpdateCompass(PluginCommands.java:52) ~[?:?]
639 | at com.yoonicode.minecraftmanhunt.PluginCommands$3.run(PluginCommands.java:299) ~[?:?]
640 | at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
641 | at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
642 | at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1059) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
643 | at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:349) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
644 | at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
645 | at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
646 | at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[minecraft_server.jar:git-Spigot-57bbdd8-dea4138]
647 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

Paste relevant console warnings/errors here
```


## Anything else?
Add any other context about the problem here.
