### ISSUE TITLE
Bot joining and leaving

### ISSUE THREAD

**Issue by tired9494** [yummypasta/MinecraftManhunt#63]
The bot keeps on leaving and rejoining when I do any music commands.

Newest plugin version

Newest papermc version but also occurs on latest spigot version

## Configuration file
Sending us your plugin `config.yml` file may help in diagnosing the issue. Paste the contents of the plugin's config file here: (feel free to omit your Discord token for security reasons)
```yaml
# How long the hunters should get blindness and slowness when the match starts.
headStartDuration: 4
compassEnabledInNether: true
setRunnersToSpecOnDeath: true
sendUsageData: true
huntersColor: '&c'
runnersColor: '&a'
spectatorsColor: '&b'
enableDiscord: true
discordToken: ODI1......
ip: ....
processDiscordCommands: false
discordServerId: 8225286....
musicChannelId: 825345023012372492
hunterRoleId: XXXXX
runnerRoleId: XXXXX
spectatorRoleId: XXXXX
uuid: 63b4ee44-f3ff-4df4-9bc6-28693547cd6b
```

```
28.03 14:07:33 [Server] INFO ... issued server command: /music approaching
28.03 14:07:34 [Server] INFO Loaded track approaching
28.03 14:07:34 [Server] INFO Audio track start callback called
28.03 14:07:34 [Server] INFO Started track with a result of true
```
No errors in logs/console

Edit: I tried a different server host and it works fine now. Do I have to ask the old host to fix their system times if that's the issue?
