### ISSUE TITLE
Music doesn't work anymore

### ISSUE THREAD

**Issue by larssieboy18** [yummypasta/MinecraftManhunt#65]
## Describe the bug
Most of the music doesn't work anymore. In the log you can see that most of the songs are not working, because there is some error related to Youtube.

## Potential Causes
No clue. Did not change anything, the music just stopped working. Based on a quick look, it looks like an error related to YouTube.

## Environment Info
**Plugin version:** 1.3.3.6

**Bukkit/Spigot server version:** Purpur 710, v. 1.16.1

## Configuration file
Sending us your plugin `config.yml` file may help in diagnosing the issue. Paste the contents of the plugin's config file here: (feel free to omit your Discord token for security reasons)
```yaml
# How long the hunters should get blindness and slowness when the match starts.
headStartDuration: 30
compassEnabledInNether: true
setRunnersToSpecOnDeath: true
sendUsageData: true
huntersColor: '&c'
runnersColor: '&a'
spectatorsColor: '&b'
enableDiscord: true
discordToken: xxx
ip: play.creeper.town
processDiscordCommands: true
discordServerId: 791691919842738187
musicChannelId: 824002563249930240
hunterRoleId: 823600420555325500
runnerRoleId: 823600482563260476
spectatorRoleId: 823600465609883688
uuid: 1a5d54b3-2864-43eb-8a9e-544402479a95
```

## Server Logs
Please check your Server Console for any warnings or errors created by the plugin. If any are any, please copy and paste them here:

[https://larssieboy18.stackstorage.com/s/QFqQwLRVdDFry61p](https://larssieboy18.stackstorage.com/s/QFqQwLRVdDFry61p)
